version: '3.4'

services:
  weathermonitoring.pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - weathermonitoring.postgresql

  weathermonitoring.postgresql:
    image: postgres:14.1

  weathermonitoring.server:
    image: ${DOCKER_REGISTRY-}weathermonitoringserver
    build:
      context: .
      dockerfile: WeatherMonitoring.Server/Dockerfile
    depends_on:
      - weathermonitoring.pgadmin
    restart: always