// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WeatherMonitoring.Context;

#nullable disable

namespace WeatherMonitoring.Context.Migrations.PgSql.Migrations
{
    [DbContext(typeof(MainDbContext))]
    partial class MainDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WeatherMonitoring.Context.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("Country")
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("country");

                    b.Property<bool>("Included")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("included");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision")
                        .HasColumnName("lat");

                    b.Property<double>("Lon")
                        .HasColumnType("double precision")
                        .HasColumnName("lon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("name");

                    b.Property<string>("Region")
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("region");

                    b.Property<string>("TzId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tz_id");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Uid")
                        .IsUnique();

                    b.ToTable("Location", "wmapp");
                });

            modelBuilder.Entity("WeatherMonitoring.Context.Entities.Weather", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConditionCode")
                        .HasColumnType("integer")
                        .HasColumnName("c_code");

                    b.Property<string>("ConditionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("c_text");

                    b.Property<int>("Humidity")
                        .HasColumnType("integer")
                        .HasColumnName("humidity");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastup");

                    b.Property<long>("LastUpdatedEpoch")
                        .HasColumnType("bigint")
                        .HasColumnName("lastup_epoch");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.Property<double>("PressureIn")
                        .HasColumnType("double precision")
                        .HasColumnName("pressure_in");

                    b.Property<double>("TemperatureCelsius")
                        .HasColumnType("double precision")
                        .HasColumnName("temp_c");

                    b.Property<double>("WindSpeedKph")
                        .HasColumnType("double precision")
                        .HasColumnName("wind_kph");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Weather", "wmapp");
                });

            modelBuilder.Entity("WeatherMonitoring.Context.Entities.Weather", b =>
                {
                    b.HasOne("WeatherMonitoring.Context.Entities.Location", "Location")
                        .WithMany("Weathers")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("WeatherMonitoring.Context.Entities.Location", b =>
                {
                    b.Navigation("Weathers");
                });
#pragma warning restore 612, 618
        }
    }
}
